#!/bin/bash

# ========================================
# 奥领数控品控系统 - 完整自动配置脚本
# ========================================

echo "======================================"
echo "奥领数控品控系统 - 完整自动配置"
echo "======================================"
echo ""

# 检查是否在正确的目录
if [ ! -f "app-supabase.js" ]; then
    echo "❌ 错误：请在 static 目录下运行此脚本"
    echo "   当前目录: $(pwd)"
    exit 1
fi

echo "请按照以下步骤操作："
echo ""
echo "======================================"
echo "第1步：获取 Supabase API 信息"
echo "======================================"
echo ""
echo "1. 在浏览器中打开：https://supabase.com/dashboard"
echo "2. 登录您的账号：frank0321@126.com"
echo "3. 选择项目：qc-system"
echo "4. 点击左侧菜单 Settings → API"
echo "5. 复制以下两个值："
echo "   - Project URL（例如：https://xxxxxxxxxxxxx.supabase.co）"
echo "   - anon public key（一长串字符）"
echo ""
echo "======================================"
echo "第2步：配置前端应用"
echo "======================================"
echo ""

# 获取 Supabase URL
read -p "请输入 Supabase Project URL: " supabase_url

# 验证 URL 格式
if [[ ! $supabase_url =~ ^https://.*\.supabase\.co$ ]]; then
    echo ""
    echo "❌ 错误：URL 格式不正确"
    echo "   正确格式：https://xxxxxxxxxxxxx.supabase.co"
    echo ""
    echo "请从 Supabase Dashboard → Settings → API 获取正确的 URL"
    exit 1
fi

# 获取 Supabase Anon Key
read -p "请输入 Supabase anon public key: " supabase_key

# 验证 Key 格式
if [[ ! $supabase_key =~ ^eyJ[a-zA-Z0-9_-]+\.[a-zA-Z0-9_-]+\.[a-zA-Z0-9_-]+$ ]]; then
    echo ""
    echo "⚠️  警告：Key 格式可能不正确"
    echo "   正确格式应该以 eyJ 开头"
    echo ""
    read -p "是否继续？(y/n): " confirm
    if [[ $confirm != "y" && $confirm != "Y" ]]; then
        echo "已取消"
        exit 0
    fi
fi

echo ""
echo "======================================"
echo "配置信息："
echo "======================================"
echo "URL: $supabase_url"
echo "Key: ${supabase_key:0:50}..."
echo ""

# 确认配置
read -p "确认以上配置信息正确？(y/n): " confirm

if [[ $confirm != "y" && $confirm != "Y" ]]; then
    echo "已取消"
    exit 0
fi

echo ""
echo "正在配置..."
echo ""

# 备份原文件
if [ -f "app-supabase.js" ]; then
    cp app-supabase.js app-supabase.js.backup
    echo "✅ 已备份原文件到 app-supabase.js.backup"
fi

# 替换配置
sed -i '' "s|YOUR_SUPABASE_URL|$supabase_url|g" app-supabase.js
sed -i '' "s|YOUR_SUPABASE_ANON_KEY|$supabase_key|g" app-supabase.js

echo "✅ 前端配置完成！"
echo ""

# 创建数据库 SQL 文件
cat > database-setup.sql << 'EOF'
-- ========================================
-- 奥领数控品控系统 - 数据库初始化
-- ========================================

-- 1. 创建设备表
CREATE TABLE IF NOT EXISTS devices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  device_number TEXT UNIQUE NOT NULL,
  model TEXT NOT NULL,
  customer TEXT NOT NULL,
  order_number TEXT NOT NULL,
  status TEXT DEFAULT 'assembling',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. 创建组装检测表
CREATE TABLE IF NOT EXISTS assembly_checks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  device_id BIGINT REFERENCES devices(id) ON DELETE CASCADE,
  check_item TEXT NOT NULL,
  description TEXT,
  photo_path TEXT,
  inspector TEXT,
  status TEXT DEFAULT 'pending',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. 创建测试报告表
CREATE TABLE IF NOT EXISTS test_reports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  device_id BIGINT REFERENCES devices(id) ON DELETE CASCADE,
  test_item TEXT NOT NULL,
  standard TEXT,
  result TEXT,
  tester TEXT,
  test_date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  confirmed BOOLEAN DEFAULT FALSE
);

-- 4. 创建发货清点表
CREATE TABLE IF NOT EXISTS shipping_checks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  device_id BIGINT REFERENCES devices(id) ON DELETE CASCADE,
  item_name TEXT NOT NULL,
  item_type TEXT,
  required_quantity INTEGER,
  actual_quantity INTEGER,
  checker TEXT,
  status TEXT DEFAULT 'pending',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. 创建客户反馈表
CREATE TABLE IF NOT EXISTS customer_feedback (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  device_id BIGINT REFERENCES devices(id) ON DELETE CASCADE,
  feedback_type TEXT,
  description TEXT,
  rating INTEGER,
  customer TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 6. 创建改进建议表
CREATE TABLE IF NOT EXISTS improvement_suggestions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  device_id BIGINT REFERENCES devices(id) ON DELETE CASCADE,
  suggestion TEXT,
  priority TEXT,
  status TEXT DEFAULT 'pending',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ========================================
-- 启用行级安全策略
-- ========================================

ALTER TABLE devices ENABLE ROW LEVEL SECURITY;
ALTER TABLE assembly_checks ENABLE ROW LEVEL SECURITY;
ALTER TABLE test_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE shipping_checks ENABLE ROW LEVEL SECURITY;
ALTER TABLE customer_feedback ENABLE ROW LEVEL SECURITY;
ALTER TABLE improvement_suggestions ENABLE ROW LEVEL SECURITY;

-- ========================================
-- 创建安全策略（测试阶段 - 允许所有访问）
-- ========================================

DROP POLICY IF EXISTS "Enable all for devices" ON devices;
CREATE POLICY "Enable all for devices" ON devices
  FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Enable all for assembly_checks" ON assembly_checks;
CREATE POLICY "Enable all for assembly_checks" ON assembly_checks
  FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Enable all for test_reports" ON test_reports;
CREATE POLICY "Enable all for test_reports" ON test_reports
  FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Enable all for shipping_checks" ON shipping_checks;
CREATE POLICY "Enable all for shipping_checks" ON shipping_checks
  FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Enable all for customer_feedback" ON customer_feedback;
CREATE POLICY "Enable all for customer_feedback" ON customer_feedback
  FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Enable all for improvement_suggestions" ON improvement_suggestions;
CREATE POLICY "Enable all for improvement_suggestions" ON improvement_suggestions
  FOR ALL USING (true) WITH CHECK (true);

-- ========================================
-- 创建索引以提高查询性能
-- ========================================

CREATE INDEX IF NOT EXISTS idx_devices_device_number ON devices(device_number);
CREATE INDEX IF NOT EXISTS idx_devices_status ON devices(status);
CREATE INDEX IF NOT EXISTS idx_assembly_checks_device_id ON assembly_checks(device_id);
CREATE INDEX IF NOT EXISTS idx_test_reports_device_id ON test_reports(device_id);
CREATE INDEX IF NOT EXISTS idx_shipping_checks_device_id ON shipping_checks(device_id);
CREATE INDEX IF NOT EXISTS idx_customer_feedback_device_id ON customer_feedback(device_id);
CREATE INDEX IF NOT EXISTS idx_improvement_suggestions_device_id ON improvement_suggestions(device_id);

-- ========================================
-- 插入测试数据
-- ========================================

-- 设备 1
INSERT INTO devices (device_number, model, customer, order_number, status)
VALUES ('CNC-2024-001', 'XK7132', '华东机械制造有限公司', 'ORDER-2024-001', 'assembling')
ON CONFLICT (device_number) DO NOTHING;

-- 设备 2
INSERT INTO devices (device_number, model, customer, order_number, status)
VALUES ('CNC-2024-002', 'XK7140', '北方精密仪器厂', 'ORDER-2024-002', 'testing')
ON CONFLICT (device_number) DO NOTHING;

-- 设备 3
INSERT INTO devices (device_number, model, customer, order_number, status)
VALUES ('CNC-2024-003', 'XK7132', '南方汽车零部件公司', 'ORDER-2024-003', 'shipping')
ON CONFLICT (device_number) DO NOTHING;

-- ========================================
-- 完成
-- ========================================

-- 显示创建的表
SELECT 
  table_name,
  (SELECT COUNT(*) FROM information_schema.columns WHERE table_name = t.table_name) as column_count
FROM information_schema.tables t
WHERE t.table_schema = 'public'
  AND t.table_name IN ('devices', 'assembly_checks', 'test_reports', 'shipping_checks', 'customer_feedback', 'improvement_suggestions')
ORDER BY table_name;
EOF

echo "✅ 已创建数据库 SQL 文件：database-setup.sql"
echo ""

echo "======================================"
echo "第3步：创建数据库表"
echo "======================================"
echo ""
echo "请按照以下步骤在 Supabase 中创建数据库表："
echo ""
echo "1. 在浏览器中打开：https://supabase.com/dashboard/project/qc-system"
echo "2. 点击左侧菜单 SQL Editor"
echo "3. 点击 New query 按钮"
echo "4. 打开文件：database-setup.sql"
echo "5. 复制所有内容"
echo "6. 粘贴到 SQL Editor 中"
echo "7. 点击 Run 按钮"
echo "8. 等待执行完成（通常几秒钟）"
echo ""

read -p "数据库表已创建？(y/n): " db_created

if [[ $db_created != "y" && $db_created != "Y" ]]; then
    echo "请先完成数据库表创建，然后再继续"
    exit 0
fi

echo ""
echo "======================================"
echo "配置结果："
echo "======================================"
echo ""

# 显示配置后的前几行
head -n 10 app-supabase.js | grep -A 2 "SUPABASE"

echo ""
echo "======================================"
echo "下一步："
echo "======================================"
echo ""
echo "1. 在浏览器中打开 index.html"
echo "   路径：$(pwd)/index.html"
echo ""
echo "2. 检查是否能看到设备列表"
echo ""
echo "3. 测试创建新设备"
echo ""
echo "4. 刷新页面，检查数据是否保存"
echo ""
echo "5. 如果一切正常，就可以部署到 Vercel 了"
echo ""
echo "======================================"
echo "配置完成！"
echo "======================================"